### ISSUE TITLE
ROS2 max_range parameter not affecting map

### ISSUE THREAD

**Issue by hofbauerc** [facontidavide/Bonxai#25]
Hi,

I am currently using different parameters for the ROS2 node of the bonxai implementation. However, changing the sensor_model/max_range currently does not affect the map build process.

As described in the bonxai_ros section (https://github.com/facontidavide/Bonxai/tree/main/bonxai_ros) the max_range should be deactivated with -1.0, which is indeed the case. However, changing this value to something like 5.0 or 10.0 does not change the map building process. 

Is this a bug or am I missing something?

Thanks in advance!

This is my current config:

    bonxai_server_node:
      ros__parameters:
        resolution: 0.05
        frame_id: "world"
        base_frame_id: "livox_frame"
    
        occupancy_min_z: -10.0
        occupancy_max_z: 20.0
    
        sensor_model:
          max_range: 5.0
          hit: 0.85
          miss: 0.3
          min: 0.12
          max: 0.97
    
        latch: false

**Comment by ivrolan** [comment]
Hi,

It seems that the param `max_range` was declared but not used in `bonxai_server.cpp`. Take a look to #28, it should fix it.
