### ISSUE TITLE
Issue with the scale of Bonxai::ProbabilisticMap

### ISSUE THREAD

**Issue by Josgonmar** [facontidavide/Bonxai#27]
First of all, thank you so much for your awesome work!

I've been trying to get the free space from a point cloud scan making use of the Bonxai::ProbabilisticMap class just like you would do it using Octomap, but i found out that the parameter that in the example code you call resolution, does not change the resolution of the map but its scale instead.

My code is looks like this:

    pcl::PointCloud<pcl::PointXYZ>::Ptr raw_depth_cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::fromROSMsg(*msg, *raw_depth_cloud);

    bonxai_ = std::make_unique<Bonxai::ProbabilisticMap>(resolution_);
    Bonxai::ProbabilisticMap::Options opt = {
        bonxai_->logods(0.4), bonxai_->logods(0.7), bonxai_->logods(0.12), bonxai_->logods(0.97)};
    bonxai_->setOptions(opt);

    const pcl::PointXYZ sensor_og(0, 0, 0);
    bonxai_->insertPointCloud(raw_depth_cloud->points, sensor_og, 20.0);

    std::vector<Bonxai::CoordT> free_coords;
    bonxai_->getFreeVoxels(free_coords);

    std::vector<Bonxai::CoordT> occ_coords;
    bonxai_->getOccupiedVoxels(occ_coords);

    pcl::PointCloud<pcl::PointXYZ>::Ptr free_points(new pcl::PointCloud<pcl::PointXYZ>);

    for (const auto& voxel : occ_coords) {
        const pcl::PointXYZ pt(voxel.x, voxel.y, voxel.z);
        free_points->points.push_back(pt);
    }

    free_points->width  = free_points->points.size();
    free_points->height = 1;

    sensor_msgs::PointCloud2 free_msg;
    pcl::toROSMsg(*free_points, free_msg);

    free_msg.header.frame_id = msg->header.frame_id;
    free_msg.header.stamp    = ros::Time::now();
    freespace_cloud_pub_.publish(free_msg);

Seems pretty straightforward. But with a resolution of 0.1 i get:
![res_01](https://github.com/facontidavide/Bonxai/assets/83069965/e9521411-5463-48cd-bdbd-8c2cc87d278a)

And using a resolution of 1.0:
![res_1](https://github.com/facontidavide/Bonxai/assets/83069965/d9dd272f-b1f6-4292-9afd-d1ace9510e71)

Am I doing something wrong?

Thanks in advance!

**Comment by facontidavide** [comment]
You are missing the conversion from CoordT to real numbers.

https://github.com/facontidavide/Bonxai/blob/main/bonxai_core/include/bonxai/bonxai.hpp#L99-L104
