### ISSUE TITLE
Bug causes by value() before setValue() 

### ISSUE THREAD

**Issue by getupgetup** [facontidavide/Bonxai#3]
Thanks for your great work. I'm using your VoxelGrid to replace my own grid so that performance can be improved. However, I got a problem. Here's my pseudo code:
/* pesudor code
auto ptr = accessor.value(coord);
if(ptr){
 DoSomething();
}
else{
 accessor.setValue(coord, new_value);
}
*/
If ptr is nullptr(coord has not been setValue before), error happens!
"prev_leaf_ptr_ = getLeafGrid(coord, false)" in value() makes prev_leaf_ptr_  nullptr, 
then "prev_leaf_ptr_->mask.setOn(index)" in setValue() caused segmentfault.
Is there anything I'm missing?
Thank you.

**Comment by facontidavide** [comment]
Thanks for reporting, I will have a look at it

**Comment by facontidavide** [comment]
thanks again
