### ISSUE TITLE
vdbfusion

### ISSUE THREAD

**Issue by nachovizzo** [facontidavide/Bonxai#4]
Hello there! Great work, I wonder how this might speed up the [vdbfusion](https://github.com/PRBonn/vdbfusion) pipeline. Any interest in giving this a try?

To try the current implementation just `pip install vdbfusion` and play around, there is also a thin simple `C++` API in case you don't want to use Python.

Best!

**Comment by facontidavide** [comment]
this is not on my TODO list, but thanks for the link

**Comment by facontidavide** [comment]
As a follow-up: I don't think you will see any speedup.
The advantage would be removing a big dependency for a small one, but that's it.
