### ISSUE TITLE
ROS support?

### ISSUE THREAD

**Issue by james-yoo** [facontidavide/Bonxai#6]
@facontidavide 
Thanks for your great work and contribution for open source ecosystem!
I would like to know any progress on integration with ROS/ROS2.

**Comment by facontidavide** [comment]
Bonxai is 3 files.... just copy and paste in your project as 3rd party library!

https://github.com/facontidavide/Bonxai/tree/main/include/bonxai

Do you mean something else?

**Comment by james-yoo** [comment]
Thanks for your quick response.
'Integration with ROS' is in the README, so I just wanted to check it.
