### ISSUE TITLE
Trversal

### ISSUE THREAD

**Issue by jimbok8** [facontidavide/Bonxai#7]
Do you have any code/benchmarks for tree traversal?
I am thinking of collision detection techniques where you need to traverse down 2 tree looking for intersections (narrowphase).
Thanks
Jim

**Comment by facontidavide** [comment]
By traversal, I think you mean iterating through all the active voxel (?)

If so, it is already one of the benchmarks

**Comment by facontidavide** [comment]
Also, if you want to do fast collision check of two trees, it is important to consider using the hierarchical bonding boxes (not documented yet, more details will be posted after ROSCon 2023).

By the end of the year (don't keep your breath) I might look into it.

**Comment by tejalbarnwal** [comment]
> Also, if you want to do fast collision check of two trees, it is important to consider using the hierarchical bounding boxes to perform broad phase collision check.
(not documented yet, more details will be posted after ROSCon 2023).
By the end of the year (don't keep your breath) I might look into it.

@facontidavide , could you elaborate on the method you suggested above for using the hierarchical bounding boxes to perform broad phase collision check? I am looking into to try bonxai for 3D planning with FCL and OMPL
